services:
   portfolio:
      image: ghcr.io/ola-awaly/portfolio:latest

      ports:
         - '8080:8090'
      pull_policy: always
      networks:
         - proxy_portfolio

networks:
   proxy_portfolio:
      external: true
